DROP TABLE IF EXISTS `Child_Assess`;

CREATE TABLE `Child_Assess` ( `oid` INT(11) NULL DEFAULT NULL , `sid` INT(11) NULL DEFAULT NULL , `sem` INT(11) NULL DEFAULT NULL , `year` YEAR NULL DEFAULT NULL , `assumed_age` INT(11) NULL DEFAULT NULL , `lang_diff` INT(11) NULL DEFAULT NULL , `q1` INT(11) NULL DEFAULT NULL , `q2` INT(11) NULL DEFAULT NULL , `q3` INT(11) NULL DEFAULT NULL , `q4` INT(11) NULL DEFAULT NULL , `q5` INT(11) NULL DEFAULT NULL , `q6` INT(11) NULL DEFAULT NULL ) ENGINE = InnoDB COMMENT = 'Child-assesment-table';
LOCK TABLES `Child_Assess` WRITE;
/*!40000 ALTER TABLE `Child_Assess` DISABLE KEYS */;
/*!40000 ALTER TABLE `Child_Assess` ENABLE KEYS */;
UNLOCK TABLES;

